import React, { useState, useEffect } from 'react';
import Navbar from './components/Navbar';
import AuthModal from './components/AuthModal';
import QuizInterface from './components/QuizInterface';
import Dashboard from './components/Dashboard';
import { User, Language, SUBJECTS } from './types';
import { getStats, updateStats } from './services/storageService';
import * as Icons from 'lucide-react';

function App() {
  const [user, setUser] = useState<User | null>(null);
  const [language, setLanguage] = useState<Language>(Language.ENGLISH);
  const [isAuthOpen, setIsAuthOpen] = useState(false);
  const [currentView, setCurrentView] = useState<'home' | 'quiz' | 'dashboard'>('home');
  const [selectedSubject, setSelectedSubject] = useState<{id: string, name: string} | null>(null);
  const [stats, setStats] = useState(getStats());

  // Check for saved user session on mount
  useEffect(() => {
    const savedUser = localStorage.getItem('prepMasterUser');
    if (savedUser) {
      setUser(JSON.parse(savedUser));
    }
  }, []);

  // Sync stats state on mount
  useEffect(() => {
    setStats(getStats());
  }, []);

  const handleLogout = () => {
    localStorage.removeItem('prepMasterUser');
    setUser(null);
    setCurrentView('home');
  };

  const startQuiz = (subjectId: string, subjectName: string) => {
    if (!user) {
      setIsAuthOpen(true);
      return;
    }
    setSelectedSubject({ id: subjectId, name: subjectName });
    setCurrentView('quiz');
  };

  const startMockExam = () => {
    startQuiz('all_subjects', 'Full Mock Exam');
  };

  const handleQuestionAnswered = (isCorrect: boolean) => {
    if (selectedSubject) {
      const newStats = updateStats(selectedSubject.id, isCorrect);
      setStats(newStats);
    }
  };

  const DynamicIcon = ({ name }: { name: string }) => {
    // @ts-ignore
    const IconComponent = Icons[name];
    return IconComponent ? <IconComponent className="h-8 w-8" /> : null;
  };

  return (
    <div className="min-h-screen bg-slate-50 font-sans">
      <Navbar
        user={user}
        currentLanguage={language}
        onLanguageChange={setLanguage}
        onLoginClick={() => setIsAuthOpen(true)}
        onLogout={handleLogout}
        onHomeClick={() => {
            setCurrentView('home');
            setSelectedSubject(null);
        }}
        onDashboardClick={() => {
          setCurrentView('dashboard');
          setSelectedSubject(null);
        }}
      />

      <AuthModal
        isOpen={isAuthOpen}
        onClose={() => setIsAuthOpen(false)}
        onLoginSuccess={(userData) => setUser(userData)}
      />

      <main className="pb-20">
        {currentView === 'home' && (
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
            {/* Hero Section */}
            <div className="text-center mb-16">
              <h1 className="text-4xl md:text-5xl font-bold text-slate-900 mb-6 tracking-tight">
                Master Your <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary-600 to-indigo-600">Competitive Exams</span>
              </h1>
              <p className="text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed mb-8">
                Unlimited practice questions generated by AI. Select a subject below to start your journey to success.
              </p>
              
              <button
                onClick={startMockExam}
                className="inline-flex items-center gap-3 bg-primary-600 hover:bg-primary-700 text-white px-8 py-4 rounded-full font-bold text-lg transition-all shadow-xl shadow-primary-500/30 hover:shadow-2xl hover:shadow-primary-500/40 hover:-translate-y-1"
              >
                <Icons.Zap className="h-5 w-5 fill-current text-yellow-300" />
                Start Full Mock Exam
              </button>
            </div>

            {/* Full Mock Exam Banner */}
            <div className="mb-16 transform hover:-translate-y-1 transition-transform duration-300">
              <div className="bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 rounded-3xl p-8 md:p-10 shadow-2xl relative overflow-hidden group border border-slate-700">
                {/* Decorative Elements */}
                <div className="absolute top-0 right-0 w-64 h-64 bg-primary-500/10 rounded-full blur-3xl -mr-16 -mt-16 group-hover:bg-primary-500/20 transition-all duration-700"></div>
                <div className="absolute bottom-0 left-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl -ml-16 -mb-16 group-hover:bg-indigo-500/20 transition-all duration-700"></div>
                
                <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-8">
                  <div className="text-center md:text-left">
                    <div className="flex items-center justify-center md:justify-start gap-3 mb-3">
                       <span className="px-3 py-1 rounded-full bg-yellow-500/20 text-yellow-400 border border-yellow-500/30 text-xs font-bold uppercase tracking-wider">Recommended</span>
                    </div>
                    <h2 className="text-3xl md:text-4xl font-bold text-white mb-4 flex items-center justify-center md:justify-start gap-3">
                      <Icons.GraduationCap className="h-10 w-10 text-yellow-400" />
                      Comprehensive Mock Test
                    </h2>
                    <p className="text-slate-300 max-w-xl text-lg leading-relaxed">
                      Simulate the real exam experience with a comprehensive mixed test covering General Science, GK, Math, English, and more.
                    </p>
                  </div>
                  
                  <div className="flex-shrink-0">
                    <button
                      onClick={startMockExam}
                      className="bg-yellow-400 hover:bg-yellow-500 text-slate-900 px-8 py-4 rounded-xl font-bold text-lg transition-all shadow-[0_0_20px_rgba(250,204,21,0.3)] hover:shadow-[0_0_30px_rgba(250,204,21,0.5)] flex items-center gap-3 transform group-hover:scale-105"
                    >
                      <Icons.PlayCircle className="h-6 w-6" />
                      Start Mock Exam
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-4 mb-8">
              <div className="h-px bg-slate-200 flex-grow"></div>
              <h2 className="text-slate-500 font-semibold uppercase tracking-wider text-sm">Or Practice by Subject</h2>
              <div className="h-px bg-slate-200 flex-grow"></div>
            </div>

            {/* Subject Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {SUBJECTS.map((sub) => (
                <button
                  key={sub.id}
                  onClick={() => startQuiz(sub.id, sub.name)}
                  className="group bg-white p-6 rounded-2xl border border-slate-200 hover:border-primary-200 hover:shadow-xl hover:shadow-primary-900/5 transition-all duration-300 text-left relative overflow-hidden"
                >
                  <div className="absolute top-0 right-0 w-24 h-24 bg-primary-50 rounded-bl-full -mr-4 -mt-4 transition-transform group-hover:scale-110"></div>
                  
                  <div className="relative z-10">
                    <div className="bg-white w-14 h-14 rounded-xl shadow-sm border border-slate-100 flex items-center justify-center text-primary-600 mb-4 group-hover:text-primary-700 group-hover:scale-110 transition-transform">
                      <DynamicIcon name={sub.icon} />
                    </div>
                    <h3 className="text-lg font-bold text-slate-900 mb-1 group-hover:text-primary-700 transition-colors">
                      {sub.name}
                    </h3>
                    <p className="text-sm text-slate-500">Start Practice &rarr;</p>
                  </div>
                </button>
              ))}
            </div>

            {/* Features Info */}
            <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
              <div className="p-6">
                <div className="w-12 h-12 bg-green-100 text-green-600 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Icons.Zap className="h-6 w-6" />
                </div>
                <h3 className="font-semibold text-slate-900 mb-2">Instant Updates</h3>
                <p className="text-slate-500 text-sm">New questions are generated in real-time based on the latest exam patterns.</p>
              </div>
              <div className="p-6">
                <div className="w-12 h-12 bg-purple-100 text-purple-600 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Icons.Languages className="h-6 w-6" />
                </div>
                <h3 className="font-semibold text-slate-900 mb-2">Multi-lingual</h3>
                <p className="text-slate-500 text-sm">Practice in English, Bengali, or Hindi to ensure you understand every concept.</p>
              </div>
              <div className="p-6">
                <div className="w-12 h-12 bg-orange-100 text-orange-600 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Icons.Brain className="h-6 w-6" />
                </div>
                <h3 className="font-semibold text-slate-900 mb-2">AI Explanations</h3>
                <p className="text-slate-500 text-sm">Detailed explanations for every answer to help you learn from mistakes.</p>
              </div>
            </div>
          </div>
        )}

        {currentView === 'dashboard' && (
          <Dashboard 
            stats={stats} 
            onHomeClick={() => {
              setCurrentView('home');
              setSelectedSubject(null);
            }} 
          />
        )}

        {currentView === 'quiz' && selectedSubject && (
          <QuizInterface
            subject={selectedSubject.id}
            subjectName={selectedSubject.name}
            language={language}
            onExit={() => {
              setCurrentView('home');
              setSelectedSubject(null);
            }}
            onAnswer={handleQuestionAnswered}
          />
        )}
      </main>
    </div>
  );
}

export default App;